# Generated by Django 5.2 on 2025-05-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('sensor', 'SENSOR'), ('actuator', 'ACTUATOR'), ('switch', 'SWITCH')], max_length=20),
        ),
    ]
