# Generated by Django 5.2 on 2025-05-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_device_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='localtion',
            new_name='location',
        ),
    ]
